services:
  postgres:
    image: postgres:13.8-bullseye
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./tmp/postgres-data
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  redis: 
    image: redis:6.0.16-bullseye
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./tmp/redis-data
        target: /data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  configsvr1:
    container_name: configsvr1
    extends:
      file: ./shard_mongo/config_server/docker-compose.yaml
      service: configsvr1
  configsvr2:
    container_name: configsvr2
    extends:
      file: ./shard_mongo/config_server/docker-compose.yaml
      service: configsvr2
  configsvr3:
    container_name: configsvr3
    extends:
      file: ./shard_mongo/config_server/docker-compose.yaml
      service: configsvr3

  shardsvr1_1:
    container_name: shardsvr1_1
    extends:
      file: ./shard_mongo/shard_server1/docker-compose.yaml
      service: shardsvr1_1
    depends_on:
      configsvr1:
        condition: service_started
      configsvr2:
        condition: service_started
      configsvr3:
        condition: service_started
  shardsvr1_2:
    container_name: shardsvr1_2
    extends:
      file: ./shard_mongo/shard_server1/docker-compose.yaml
      service: shardsvr1_2
    depends_on:
      configsvr1:
        condition: service_started
      configsvr2:
        condition: service_started
      configsvr3:
        condition: service_started
  shardsvr1_3:
    container_name: shardsvr1_3
    extends:
      file: ./shard_mongo/shard_server1/docker-compose.yaml
      service: shardsvr1_3
    depends_on:
      configsvr1:
        condition: service_started
      configsvr2:
        condition: service_started
      configsvr3:
        condition: service_started

  shardsvr2_1:
    container_name: shardsvr2_1
    extends:
      file: ./shard_mongo/shard_server2/docker-compose.yaml
      service: shardsvr2_1
    depends_on:
      configsvr1:
        condition: service_started
      configsvr2:
        condition: service_started
      configsvr3:
        condition: service_started
  shardsvr2_2:
    container_name: shardsvr2_2
    extends:
      file: ./shard_mongo/shard_server2/docker-compose.yaml
      service: shardsvr2_2
    depends_on:
      configsvr1:
        condition: service_started
      configsvr2:
        condition: service_started
      configsvr3:
        condition: service_started
  shardsvr2_3:
    container_name: shardsvr2_3
    extends:
      file: ./shard_mongo/shard_server2/docker-compose.yaml
      service: shardsvr2_3
    depends_on:
      configsvr1:
        condition: service_started
      configsvr2:
        condition: service_started
      configsvr3:
        condition: service_started

  mongo:
    container_name: mongo
    extends:
      file: ./shard_mongo/mongo_router/docker-compose.yaml
      service: mongo
    hostname: mongo
    restart: always
    depends_on:
      configsvr1:
        condition: service_started
      configsvr2:
        condition: service_started
      configsvr3:
        condition: service_started

  neo:
    image: neo4j:5.1.0
    hostname: neo
    container_name: neo
    restart: always
    environment:
      - NEO4J_AUTH=none
      - NEO4J_server.bolt.advertised_address=neo:7687
    ports:
        - "7474:7474"
        - "7687:7687"
    volumes:
      - ./tmp/neo4j-data:/data

  zookeeper:
    container_name: zookeeper
    image: ubuntu/zookeeper:edge
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: ubuntu/kafka:3.1-22.04_edge
    ports:
      - "9092:9092"
    environment:
      - TZ=UTC+2
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
    hostname: kafka
    depends_on:
      - zookeeper

  event-streaming:
    build:
      context: ./event_streaming
      dockerfile: Dockerfile
    image: nmngo248/event-streaming:latest
    container_name: event-streaming
    ports:
      - "8000:8000"
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=deng
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Paris
    hostname: event-streaming
    depends_on:
      - kafka
      - mongo
      - postgres


  # redis-dayofweek:
  #   build:
  #     context: ./redis_dayofweek
  #     dockerfile: Dockerfile
  #   image: nmngo248/redis-dayofweek:latest
  #   container_name: redis-dayofweek
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_DB=0
  #   depends_on:
  #     - redis

  postgres-airflow:
    container_name: postgres-airflow
    extends:
      file: airflow-compose.yaml
      service: postgres-airflow
  redis-airflow:
    container_name: redis-airflow
    extends:
      file: airflow-compose.yaml
      service: redis-airflow
  airflow-webserver:
    container_name: airflow-webserver
    extends:
      file: airflow-compose.yaml
      service: airflow-webserver
  airflow-scheduler:
    container_name: airflow-scheduler
    extends:
      file: airflow-compose.yaml
      service: airflow-scheduler
  airflow-worker:
    container_name: airflow-worker
    extends:
      file: airflow-compose.yaml
      service: airflow-worker  
  airflow-init:
    container_name: airflow-init
    profiles: ["init"]
    extends:
      file: airflow-compose.yaml
      service: airflow-init
  flower:
    container_name: airflow-flower
    extends:
      file: airflow-compose.yaml
      service: flower
networks:
  default:
    name: meteorif