version: '3'

services:
  configsvr1:
    container_name: configsvr1
    image: mongo:6.0.2-focal
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017
    ports:
      - 10001:27017
    volumes:
      - type: bind
        source: ../../tmp/mongo-data-svr1
        target: /data/db

  configsvr2:
    container_name: configsvr2
    image: mongo:6.0.2-focal
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017
    ports:
      - 10002:27017
    volumes:
      - type: bind
        source: ../../tmp/mongo-data-svr2
        target: /data/db

  configsvr3:
    container_name: configsvr3
    image: mongo:6.0.2-focal
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017
    ports:
      - 10003:27017
    volumes:
      - type: bind
        source: ../../tmp/mongo-data-svr3
        target: /data/db
